### ISSUE TITLE
Onelog out of sync with most recent Gojay changes

### ISSUE THREAD

**Issue by zcnewt** [francoispqt/onelog#7]
Bonjour Francois,
First off, I like this project! Especially chaining.

It looks like some recent changes to Gojay broke Onelog.

Perhaps all that needs to be changed is to update to new names in Onelog?

Currently what I'm seeing when trying to go get:
```
➜  go get github.com/francoispqt/onelog
# github.com/francoispqt/onelog
../../francoispqt/onelog/entry.go:62:37: undefined: gojay.MarshalerObject
../../francoispqt/onelog/entry.go:68:36: undefined: gojay.MarshalerArray
../../francoispqt/onelog/entry.go:152:37: undefined: gojay.MarshalerObject
../../francoispqt/onelog/entry.go:161:36: undefined: gojay.MarshalerArray
```

**Comment by zcnewt** [comment]
Took a quick stab at making required changes:
https://github.com/francoispqt/onelog/pull/8

**Comment by francoispqt** [comment]
Hi, thanks for raising the issue. 

Yes onelog is out of sync with gojay, you should use `dep ensure` to have the correct version of gojay in `vendor`. I am working on moving Onelog to version 1.0.0, which will be in sync with Gojay. Will close the issue when this will be done, probably on today.

**Comment by zcnewt** [comment]
Cool. I'll just `dep` for now (this is just for personal project), but if this works out I'd love to take this for a spin in a real application.

Let me know if you would like any help.

**Comment by francoispqt** [comment]
Just updated onelog to work with latest version of gojay. Released version 0.11.2. Closing the issue. Thanks!
